name: Rubocop Lint Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Run Rubocop Linter
      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel --display-cop-names